language: node_js

node_js:
  - "0.10"

services: redis

notifications:
  irc:
    channels:
      - "irc.mozilla.org#media"
    use_notice: false
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch} - %{commit}: %{author}): %{message} %{build_url}"
